[project]
name = "proxipy"
version = "0.1.0"
description = "A **production-ready, high-performance, secure CORS proxy server** built with FastAPI to bypass same-origin policy and prevent mixed content issues. Features intelligent streaming, comprehensive security, and robust concurrency handling."
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "aiofiles>=25.1.0",
    "email-validator>=2.3.0",
    "fastapi>=0.126.0",
    "gunicorn>=23.0.0",
    "httpx[http2]>=0.28.1",
    "hypercorn>=0.18.0",
    "passlib[bcrypt]>=1.7.4",
    "pydantic>=2.12.5",
    "pydantic-settings>=2.12.0",
    "pytest>=9.0.2",
    "python-jose[cryptography]>=3.5.0",
    "python-multipart>=0.0.21",
    "pyyaml>=6.0.3",
    "redis>=7.1.0",
    "slowapi>=0.1.9",
    "websockets>=15.0.1",
]
